#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N hmmIBD_Pk_strict
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=40GB,ncpus=5
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load bcftools/1.12
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
export PATH=$PATH:/g/data/pq84/bin/hmmIBD/   
cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/05_Analyses/Population_genetics
mkdir hmmIBD/sample_miss_5/

echo "---------------------------------------"
echo "Wrangling for sample filters to be used in IBD"
awk '{print $1}' cluster_specific_maf_filters/sample_miss_5/clusters_combined.fam > exclude_tmp1.txt
bcftools view Consensus_SNPs_subset_no_MOI.vcf.gz | grep '#CHROM' | tr '\t' '\n' | sed -n '/ERR2214837/,$p' > exclude_tmp2.txt
fgrep -v -f exclude_tmp1.txt exclude_tmp2.txt > hmmIBD/sample_miss_5/exclude_tmp3.txt
cat hmmIBD/sample_miss_5/exclude_tmp3.txt dups_from_naming_error.txt lab_isolates.txt > hmmIBD/sample_miss_5/exclude.txt
rm -f exclude_tmp1.txt exclude_tmp2.txt exclude_tmp3.txt

echo "---------------------------------------"
echo "Create variant list to filter for when generating genotype file"
awk '{print $2}' cluster_specific_maf_filters/sample_miss_5/clusters_combined.bim | sed 's/:/\t/g' | awk '{print $1"\t"$2}' | uniq -u > hmmIBD/sample_miss_5/grep_patterns.tsv

echo "---------------------------------------"
echo "Create genotype file"
Rscript /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/05_Analyses/Population_genetics/hmmIBD/hmmIBD_genotype_high_qual.R

echo "---------------------------------------"
echo "Run hmmIBD"
cd hmmIBD/sample_miss_5/
hmmIBD -i hmmIBD.tsv -b exclude.txt -o Pk

echo "---------------------------------------"
echo "FINISHED"