#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N hmmIBD_Pk
#PBS -j oe
#PBS -m ae
#PBS -l walltime=48:00:00,mem=40GB,ncpus=5
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load bcftools/1.12
module load R/4.1.0 
export R_LIBS_USER="/g/data/pq84/R"
export PATH=$PATH:/g/data/pq84/bin/hmmIBD/   
cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/05_Analyses/Population_genetics

echo "---------------------------------------"
echo "Wrangling for sample filters to be used in IBD"
mkdir hmmIBD/no_lab_strains
awk '{print $1}' cluster_specific_maf_filters/clusters_combined.fam > exclude_tmp1.txt
bcftools view -h Consensus_SNPs_subset_no_MOI.vcf.gz | grep '#CHROM' | tr '\t' '\n' | sed -n '/ERR2214837/,$p' > exclude_tmp2.txt
fgrep -v -f exclude_tmp1.txt exclude_tmp2.txt > hmmIBD/no_lab_strains/exclude_1.txt
grep 'SRR' exclude_tmp2.txt | cat hmmIBD/no_lab_strains/exclude_1.txt - > hmmIBD/no_lab_strains/exclude.txt
rm -f exclude_tmp1.txt exclude_tmp2.txt hmmIBD/no_lab_strains/exclude_1.txt

echo "---------------------------------------"
echo "Create variant list to filter for when generating genotype file"
awk '{print $2}' cluster_specific_maf_filters/clusters_combined.bim | sed 's/:/\t/g' | awk '{print $1"\t"$2}' | uniq -u > hmmIBD/no_lab_strains/grep_patterns.tsv

echo "---------------------------------------"
echo "Create genotype file"
Rscript /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/05_Analyses/Population_genetics/hmmIBD/hmmIBD_genotype_file.R 

echo "---------------------------------------"
echo "Run hmmIBD"
cd hmmIBD/no_lab_strains
hmmIBD -i hmmIBD.tsv -b exclude.txt -o Pk

echo "---------------------------------------"
echo "FINISHED"