#!/bin/bash
#PBS -P pq84
#PBS -q normalbw
#PBS -N selection_clusters
#PBS -j oe
#PBS -m ae
#PBS -l walltime=8:00:00,mem=80GB,ncpus=10
#PBS -l storage=gdata/pq84+scratch/pq84
#PBS -M jacob.westaway@menzies.edu.au

echo "---------------------------------------"
echo "PBS: Job identifier is $PBS_JOBID"
echo "PBS: Job name is $PBS_JOBNAME"

echo "---------------------------------------"
echo "Define paths and load modules"
module load bcftools/1.12
module load java/jdk-8.40 
module load R/4.3.1 
export R_LIBS=$HOME/.local/lib/R_4.3:$R_LIBS
export PATH=$PATH:/g/data/pq84/bin/plink2/
source /g/data/pq84/python-3.9.2/bin/activate
export PATH=$PATH:/g/data/pq84/bin/hmmIBD/  

FASTA="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/PKA1H1/fasta"
VCF="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/04_Variant_calling/filtered/adjusted_filters/include_archived_samples"
GATK="/g/data/pq84/bin/GenomeAnalysisTK-3.8-1-0/GenomeAnalysisTK.jar"
REGIONS_TO_MASK="/g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/data/ref_genomes/regions_to_mask.list"

cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/05_Analyses/Population_genetics/


echo "---------------------------------------"
echo "Set up VCF files"

mkdir selection/cluster_spec/Mf

awk '{print $2}' cluster_specific_maf_filters/high_quality_set/Mf.bim | sed 's/:/\t/g' | awk '{print $1 "\t" $2}' > selection/cluster_spec/Mf/snp_filter.txt
cat cluster_specific_maf_filters/high_quality_set/exclude_for_Mf.txt clonal_dups.txt > selection/cluster_spec/Mf/exclude.txt
bcftools view --force-samples -R selection/cluster_spec/Mf/snp_filter.txt -S ^selection/cluster_spec/Mf/exclude.txt Consensus_SNPs_subset_no_MOI.vcf.gz | bcftools +missing2ref -o selection/cluster_spec/Mf/selection.vcf.gz
bcftools index selection/cluster_spec/Mf/selection.vcf.gz
bcftools view selection/cluster_spec/Mf/selection.vcf.gz | grep '##contig=<ID=ordered' | sed 's/##contig=<ID=//g' | sed 's/,.*//g' > selection/cluster_spec/chromosome.txt

for i in $(cat selection/cluster_spec/chromosome.txt)
    do 
        bcftools view -r $i -o selection/cluster_spec/Mf/${i}.vcf.gz selection/cluster_spec/Mf/selection.vcf.gz
    done 

mkdir selection/cluster_spec/Mn

awk '{print $2}' cluster_specific_maf_filters/high_quality_set/Mn.bim | sed 's/:/\t/g' | awk '{print $1 "\t" $2}' > selection/cluster_spec/Mn/snp_filter.txt
cat cluster_specific_maf_filters/high_quality_set/exclude_for_Mn.txt clonal_dups.txt > selection/cluster_spec/Mn/exclude.txt
bcftools view --force-samples -R selection/cluster_spec/Mn/snp_filter.txt -S ^selection/cluster_spec/Mn/exclude.txt Consensus_SNPs_subset_no_MOI.vcf.gz | bcftools +missing2ref -o selection/cluster_spec/Mn/selection.vcf.gz
bcftools index selection/cluster_spec/Mn/selection.vcf.gz
bcftools view selection/cluster_spec/Mn/selection.vcf.gz | grep '##contig=<ID=ordered' | sed 's/##contig=<ID=//g' | sed 's/,.*//g' > selection/cluster_spec/chromosome.txt

for i in $(cat selection/cluster_spec/chromosome.txt)
    do 
        bcftools view -r $i -o selection/cluster_spec/Mn/${i}.vcf.gz selection/cluster_spec/Mn/selection.vcf.gz
    done 

mkdir selection/cluster_spec/Pen

awk '{print $2}' cluster_specific_maf_filters/high_quality_set/Pen.bim | sed 's/:/\t/g' | awk '{print $1 "\t" $2}' > selection/cluster_spec/Pen/snp_filter.txt
cat cluster_specific_maf_filters/high_quality_set/exclude_for_Pen.txt clonal_dups.txt > selection/cluster_spec/Pen/exclude.txt
bcftools view --force-samples -R selection/cluster_spec/Pen/snp_filter.txt -S ^selection/cluster_spec/Pen/exclude.txt Consensus_SNPs_subset_no_MOI.vcf.gz | bcftools +missing2ref -o selection/cluster_spec/Pen/selection.vcf.gz
bcftools index selection/cluster_spec/Pen/selection.vcf.gz
bcftools view selection/cluster_spec/Pen/selection.vcf.gz | grep '##contig=<ID=ordered' | sed 's/##contig=<ID=//g' | sed 's/,.*//g' > selection/cluster_spec/chromosome.txt

for i in $(cat selection/cluster_spec/chromosome.txt)
    do 
        bcftools view -r $i -o selection/cluster_spec/Pen/${i}.vcf.gz selection/cluster_spec/Pen/selection.vcf.gz
    done 

echo "---------------------------------------"
echo "Run rehh"

cd selection/cluster_spec/Mf
Rscript /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/05_Analyses/Population_genetics/rehh.R

cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/05_Analyses/Population_genetics/selection/cluster_spec/Mn
Rscript /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/05_Analyses/Population_genetics/rehh.R

cd /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/outputs/05_Analyses/Population_genetics/selection/cluster_spec/Pen
Rscript /g/data/pq84/malaria/Parasite_and_human_genetic_risk_factors_for_Pk_malaria/scripts/05_Analyses/Population_genetics/rehh.R

echo "---------------------------------------"
echo "Finished"